version: "3.8"

networks:
    default:
        external:
            name: describo-online_default

services:
    reva:
        image: arkisto/describo-reva
        hostname: reva-gateway
        tty: true
        working_dir: "/srv/reva"
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
        volumes:
            - ./configuration:/etc/revad
            - ./data:/var/tmp/reva
        command: bash -c "./revad --dev-dir /etc/revad"
        ports:
            - 19000:19001